# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Checkout Subrepositories
      run: git submodule update --init --recursive
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Project
      run: msbuild
      
    - run: cd Ohrogon
    - run: dir
      
      
    - name: Copy Models And Textures to Build Directory
      run: echo D | xcopy /S /E /Y .\data .\Build\Debug\data
    
    - name: Create Intermediary Directory
      run: git clone "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" -b Build ./BuildBranch
   
    
    - name: Move Build into Current Directory
      run: move .\Build\Debug\ .\BuildBranch
      
    - run: cd BuildBranch
      
    - name: Commit Changes
      run: |
          git add .
          git commit -m "Build Release"
          git push
